version: "3.8"

services:

  base-api: &base-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./drizzle:/app/drizzle
      - ./drizzle.config.ts:/app/drizzle.config.ts
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml

  api:
    container_name: api
    <<: *base-api
    ports:
      - "3333:3333"
    env_file:
      - ./.env
    command: ["sh","-c", "pnpm db:migrate && pnpm dev"]
    depends_on:
      database:
        condition: service_healthy
    restart: always

  database:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  postgres_data: